apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: avatar
    run: hello
  name: hello
  namespace: avatar-test
spec:
  progressDeadlineSeconds: 60
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: avatar 
      run: hello
      service: flask
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: avatar
        run: hello
        service: flask
    spec:
      containers:
        - image: omarnbr/ava:1.0
          imagePullPolicy: Always
          name: flask
          ports:
            - containerPort: 5000
              protocol: TCP
          resources:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              cpu: 25m
              memory: 64Mi
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 3
            periodSeconds: 3
      imagePullSecrets:
        - name: registry-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
