apiVersion: v1
kind: Service
metadata:
    labels:
        app.kubernetes.io/instance: front
        app.kubernetes.io/name: front
        service: front
    name: flask
    namespace: avatar-test
spec:
    ports:
        - name: http
          port: 80
          protocol: TCP
          targetPort: 5000
    selector:
        app: avatar
        run: hello
        service: flask
    sessionAffinity: None
    type: ClusterIP
